name: PGCE Build

on: [push, pull_request]

jobs:
  build:
    name: Windows ${{ matrix.archplatform }}
    runs-on: windows-latest

    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        include:
          - {
            arch: x86_amd64,
            archplatform: x64,
            archlocation: x64,
            }
          - {
            arch: x86,
            archplatform: x86,
            archlocation: Win32,
            }
    
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: TheMrMilchmann/setup-msvc-dev@v3  # this lets us use the developer command prompt on windows
        with:
          arch: ${{ matrix.arch }}
      
      - name: Get SDL
        run: |
          .github/fetch_sdl_vc.ps1

      - name: Build SDL_image
        run: |
          msbuild VisualC/SDL_image.vcxproj /p:PlatformToolset=v143 /p:Configuration=Release /p:Platform=${{ matrix.archplatform }}

      - name: Prepare upload
        run: |
          mkdir upload_prep/lib/${{ matrix.archplatform }}
          cp VisualC/${{ matrix.archlocation }}/Release/SDL2_image.dll upload_prep/lib/${{ matrix.archplatform }}/SDL2_image.dll
          cp VisualC/${{ matrix.archlocation }}/Release/SDL2_image.lib upload_prep/lib/${{ matrix.archplatform }}/SDL2_image.lib
          cp -r VisualC/external/optional/${{ matrix.archplatform }} upload_prep/lib/${{ matrix.archplatform }}/optional

      - name: Add constant files to bundle
        if: matrix.archplatform == 'x64' # only run once, adds to same bundle as win32
        run: |
          mkdir upload_prep/include
          cp include/SDL_image.h upload_prep/include/SDL_image.h
          cp CHANGES.txt upload_prep/CHANGES.txt
          cp README.txt upload_prep/README.txt
          cp LICENSE.txt upload_prep/LICENSE.txt

      - uses: actions/upload-artifact@v3
        with:
          name: SDL-image-build
          path: upload_prep
